In [1]:
from bs4 import BeautifulSoup
import requests
res = requests.get('https://aahar.jharkhand.gov.in/district-monthly-reports/nfsa-block-reports/MQ%3D%3D/MQ%3D%3D/OA%3D%3D/MQ%3D%3D')

In [2]:
res.status_code

200

In [3]:
soup = BeautifulSoup(res.text,'html.parser')

In [4]:
table=soup.find_all('table')[1]

In [5]:
rows=table.findChildren(['tr'])

In [6]:
row1  = []
for r in rows:
    cells = r.find_all(['span','th','td'])
    row1 += [('\t'.join(c.string for c in cells if c.string))]
    #print('\t'.join(c.string for c in cells if c.string))
    #print('00000000000000000')
    #print(row1)

In [7]:

import numpy as np 


for j in range(len(row1)):
    row1[j] = row1[j].split('\t')
    for i in range(len(row1[j])):
        row1[j][i] = row1[j][i].replace('\r','')
        row1[j][i] = row1[j][i].replace('\n','')

In [32]:
import pandas as pd
df2 = pd.DataFrame(row1)
print(df2)

                   0                      1          2            3   \
0   District : BOKARO                   None       None         None
1               Sl No             Block Name  HHD Count  Transaction
2                                       None       None         None
3                   1                  BERMO         53         9595
4                   2          CHANDANKIYARI        236        39358
5                   3            CHANDRAPURA         83        19452
6                   4                   CHAS        288        58037
7                   5                  GOMIA        199        36055
8                   6                JARIDIH         87        15784
9                   7                 KASMAR         76        16459
10                  8                NAWADIH        106        24855
11                  9               PETERWAR        114        20462
12                 10  CHAS NAGAR PALIKA(MN)         92        16088
13                 11            Phusro (NA)         67         7883
14                 12  Bokaro Steel City(TA)        222        26094
15              Total                   1623     290122       263849

              4             5                 6                  7   \
0           None          None              None               None
1      Allocated   Distributed  Total Allocation  Total Distributed
2           None          None              None               None
3           8501    222,945.00              0.00         202605.000
4          36710    975,320.00              0.00         929999.000
5          17270    270,006.00        180,004.00         246481.000
6          53249  1,159,700.00        138,990.00        1096477.000
7          34021    864,825.00         49,830.00         825819.000
8          14769    374,380.00              0.00         356640.000
9          15566    403,935.00              0.00         387815.000
10         23973    641,865.00              0.00         624765.000
11         18742    494,795.00              0.00         461540.000
12         14562    218,994.00        145,996.00         203148.000
13          7009    119,874.00         79,916.00         108201.000
14         19477    314,790.00        209,860.00         248239.000
15  6,061,429.00    804,596.00           5691729             709400

                  8        9            10     11
0               None     None         None   None
1   Distribution (%)     None         None   None
2               None     None         None   None
3             10.000   222945   202605.000  90.88
4             26.000   975320   929999.000  95.35
5         164284.000   450010   246481.000  54.77
6         125662.000  1298690  1096477.000  84.43
7          46736.000   914655   825819.000  90.29
8              0.000   374380   356640.000  95.26
9              0.000   403935   387815.000  96.01
10             0.000   641865   624765.000  97.34
11             0.000   494795   461540.000  93.28
12        135422.000   364990   203148.000  55.66
13         72034.000   199790   108201.000  54.16
14        165226.000   524650   248239.000  47.32
15           6866025  6401129        93.23   None

In [33]:
from IPython.display import display
#df2.drop(index=df2.index[0])
df2 = df2.drop(2)

#df2.columns = df2.iloc[1]
df2 = df2.drop(1)
df2 = df2.drop(0)
df2.columns = ["Sl No", "Block Name", "HHD Count", "Beneficiary Count (PH Card+AAY Card)","Transaction", "Rice Allocated(kg)", "Wheat Allocated(kg)", "Rice Distributed(kg)","Wheat Distributed(kg)", "Total Allocation", "Total Distributed", "Distribution %"]
display(df2)

,Sl No,Block Name,HHD Count,Beneficiary Count (PH Card+AAY Card),Transaction,Rice Allocated(kg),Wheat Allocated(kg),Rice Distributed(kg),Wheat Distributed(kg),Total Allocation,Total Distributed,Distribution %
3,1,BERMO,53,9595,8501,"222,945.00",0.00,202605.000,10.000,222945,202605.000,90.88
4,2,CHANDANKIYARI,236,39358,36710,"975,320.00",0.00,929999.000,26.000,975320,929999.000,95.35
5,3,CHANDRAPURA,83,19452,17270,"270,006.00","180,004.00",246481.000,164284.000,450010,246481.000,54.77
6,4,CHAS,288,58037,53249,"1,159,700.00","138,990.00",1096477.000,125662.000,1298690,1096477.000,84.43
7,5,GOMIA,199,36055,34021,"864,825.00","49,830.00",825819.000,46736.000,914655,825819.000,90.29
8,6,JARIDIH,87,15784,14769,"374,380.00",0.00,356640.000,0.000,374380,356640.000,95.26
9,7,KASMAR,76,16459,15566,"403,935.00",0.00,387815.000,0.000,403935,387815.000,96.01
10,8,NAWADIH,106,24855,23973,"641,865.00",0.00,624765.000,0.000,641865,624765.000,97.34
11,9,PETERWAR,114,20462,18742,"494,795.00",0.00,461540.000,0.000,494795,461540.000,93.28
12,10,CHAS NAGAR PALIKA(MN),92,16088,14562,"218,994.00","145,996.00",203148.000,135422.000,364990,203148.000,55.66
13,11,Phusro (NA),67,7883,7009,"119,874.00","79,916.00",108201.000,72034.000,199790,108201.000,54.16
14,12,Bokaro Steel City(TA),222,26094,19477,"314,790.00","209,860.00",248239.000,165226.000,524650,248239.000,47.32
15,Total,1623,290122,263849,"6,061,429.00","804,596.00",5691729,709400,6866025,6401129,93.23,None

In [121]:
display(df2.iloc[2])

1
Sl No                          3
Block Name           CHANDRAPURA
HHD Count                     83
Transaction                19452
Allocated                  17270
Distributed           270,006.00
Total Allocation      180,004.00
Total Distributed     246481.000
Distribution (%)      164284.000
NaN                       450010
NaN                   246481.000
NaN                        54.77
Name: 5, dtype: object

In [35]:
def converter(val):
    if type(val)==str:
        val = val.replace(',','')
    if val == None:
        return float('nan')
    else:
        return float(val)
    
df2['HHD Count'] = df2['HHD Count'].apply(converter)
df2['Beneficiary Count (PH Card+AAY Card)'] = df2['Beneficiary Count (PH Card+AAY Card)'].apply(converter)
df2['Transaction'] = df2['Transaction'].apply(converter)
df2['Rice Allocated(kg)'] = df2['Rice Allocated(kg)'].apply(converter)
df2['Wheat Allocated(kg)'] = df2['Wheat Allocated(kg)'].apply(converter)
df2['Rice Distributed(kg)'] = df2['Rice Distributed(kg)'].apply(converter)
df2['Wheat Distributed(kg)'] = df2['Wheat Distributed(kg)'].apply(converter)
df2['Total Allocation'] = df2['Total Allocation'].apply(converter)
df2['Total Distributed'] = df2['Total Distributed'].apply(converter)
df2['Distribution %'] = df2['Distribution %'].apply(converter)

In [36]:
df2

,Sl No,Block Name,HHD Count,Beneficiary Count (PH Card+AAY Card),Transaction,Rice Allocated(kg),Wheat Allocated(kg),Rice Distributed(kg),Wheat Distributed(kg),Total Allocation,Total Distributed,Distribution %
3,1,BERMO,53.0,9595.0,8501.0,222945.0,0.0,202605.0,10.0,222945.0,202605.00,90.88
4,2,CHANDANKIYARI,236.0,39358.0,36710.0,975320.0,0.0,929999.0,26.0,975320.0,929999.00,95.35
5,3,CHANDRAPURA,83.0,19452.0,17270.0,270006.0,180004.0,246481.0,164284.0,450010.0,246481.00,54.77
6,4,CHAS,288.0,58037.0,53249.0,1159700.0,138990.0,1096477.0,125662.0,1298690.0,1096477.00,84.43
7,5,GOMIA,199.0,36055.0,34021.0,864825.0,49830.0,825819.0,46736.0,914655.0,825819.00,90.29
8,6,JARIDIH,87.0,15784.0,14769.0,374380.0,0.0,356640.0,0.0,374380.0,356640.00,95.26
9,7,KASMAR,76.0,16459.0,15566.0,403935.0,0.0,387815.0,0.0,403935.0,387815.00,96.01
10,8,NAWADIH,106.0,24855.0,23973.0,641865.0,0.0,624765.0,0.0,641865.0,624765.00,97.34
11,9,PETERWAR,114.0,20462.0,18742.0,494795.0,0.0,461540.0,0.0,494795.0,461540.00,93.28
12,10,CHAS NAGAR PALIKA(MN),92.0,16088.0,14562.0,218994.0,145996.0,203148.0,135422.0,364990.0,203148.00,55.66
13,11,Phusro (NA),67.0,7883.0,7009.0,119874.0,79916.0,108201.0,72034.0,199790.0,108201.00,54.16
14,12,Bokaro Steel City(TA),222.0,26094.0,19477.0,314790.0,209860.0,248239.0,165226.0,524650.0,248239.00,47.32
15,Total,1623,290122.0,263849.0,6061429.0,804596.0,5691729.0,709400.0,6866025.0,6401129.0,93.23,NaN

In [37]:
import seaborn as sns

In [45]:
sns.barplot(y = 'Total Distributed' , x = 'Block Name',data=df2)

ValueError: Could not interpret input 'Total Allocation '

In [ ]:
import openpyxl as opx 
wb = opx.load_workbook("Bokaro.xlsx")

In [ ]:
wb

In [ ]:
sheet = wb['Block wise Transaction Report']

for r in sheet.columns:
    for cell in r:
        print(cell.value)

import pandas as pd
 
dataframe1 = pd.read_excel('Bokaro.xlsx')
 
print(dataframe1)

In [ ]:
df = pd.DataFrame(sheet.values)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11
0,District : BOKARO,None,None,None,None,None,None,None,None,None,None,None
1,Sl No,Block Name,HHD Count,Beneficiary Count,Transaction,Allocated,None,Distributed,None,Total Allocation,Total Distributed,Distribution (%)
2,None,None,None,(PH Card + AAY Card),None,Rice,Wheat,Rice,Wheat,None,None,None
3,None,None,None,None,None,(Kg),(Kg),(Kg),(Kg),None,None,None
4,1,BERMO BERMO,53,9595,8501,222945,0,202605,10,222945,202605,90.88
5,2,CHANDANKIYARI CHANDANKIYARI,236,39358,36710,975320,0,929999,26,975320,929999,95.35
6,3,CHANDRAPURA CHANDRAPURA,83,19452,17270,270006,180004,246481,164284,450010,246481,54.77
7,4,CHAS CHAS,288,58037,53249,1159700,138990,1096477,125662,1298690,1096477,84.43
8,5,GOMIA GOMIA,199,36055,34021,864825,49830,825819,46736,914655,825819,90.29
9,6,JARIDIH JARIDIH,87,15784,14769,374380,0,356640,0,374380,356640,95.26
10,7,KASMAR KASMAR,76,16459,15566,403935,0,387815,0,403935,387815,96.01
11,8,NAWADIH NAWADIH,106,24855,23973,641865,0,624765,0,641865,624765,97.34
12,9,PETERWAR PETERWAR,114,20462,18742,494795,0,461540,0,494795,461540,93.28
13,10,CHAS NAGAR PALIKA(MN) CHAS NAGAR PALIKA(MN),92,16088,14562,218994,145996,203148,135422,364990,203148,55.66
14,11,Phusro (NA) Phusro (NA),67,7883,7009,119874,79916,108201,72034,199790,108201,54.16
15,12,Bokaro Steel City(TA) Bokaro Steel City(TA),222,26094,19477,314790,209860,248239,165226,524650,248239,47.32
16,Total,None,1623,290122,263849,6061429,804596,5691729,709400,6866025,6401129,93.23